apiVersion: batch/v1
kind: Job
metadata:
  name: replay-bundler
  namespace: evidence
  labels:
    app: bundler
spec:
  template:
    spec:
      containers:
        - name: bundler
          image: ghcr.io/jallybean/replay-bundler:latest
          command: ["python", "bundle.py"]
          args: ["--input", "/evidence/replay", "--output", "/evidence/hud"]
          volumeMounts:
            - name: evidence-volume
              mountPath: /evidence
      restartPolicy: Never
      volumes:
        - name: evidence-volume
          persistentVolumeClaim:
            claimName: evidence-pvc
  backoffLimit: 3