apiVersion: v1
kind: ServiceAccount
metadata:
  name: observer-sa
  namespace: jallybean-telemetry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analyst-sa
  namespace: jallybean-telemetry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: commander-sa
  namespace: jallybean-telemetry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: observer-role
  namespace: jallybean-telemetry
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: analyst-role
  namespace: jallybean-telemetry
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelines", "pipelineruns"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: commander-role
  namespace: jallybean-telemetry
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelines", "pipelineruns"]
  verbs: ["get", "list", "watch", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: observer-binding
  namespace: jallybean-telemetry
subjects:
- kind: ServiceAccount
  name: observer-sa
roleRef:
  kind: Role
  name: observer-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: analyst-binding
  namespace: jallybean-telemetry
subjects:
- kind: ServiceAccount
  name: analyst-sa
roleRef:
  kind: Role
  name: analyst-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: commander-binding
  namespace: jallybean-telemetry
subjects:
- kind: ServiceAccount
  name: commander-sa
roleRef:
  kind: Role
  name: commander-role
  apiGroup: rbac.authorization.k8s.io
