apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    user: postgres
    password: password
    jsonData:
      sslmode: 'disable'
      timescaledb: true
