apiVersion: batch/v1
kind: Job
metadata:
  name: clause-score-loop
  namespace: telemetry
  labels:
    app: scoring
spec:
  template:
    spec:
      containers:
        - name: scorer
          image: ghcr.io/jallybean/clause-scorer:latest
          command: ["python", "score.py"]
          args: ["--input", "/evidence/replay", "--output", "/evidence/score"]
          volumeMounts:
            - name: evidence-volume
              mountPath: /evidence
      restartPolicy: Never
      volumes:
        - name: evidence-volume
          persistentVolumeClaim:
            claimName: evidence-pvc
  backoffLimit: 3