apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: jallybean-telemetry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-role
  namespace: jallybean-telemetry
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-rb
  namespace: jallybean-telemetry
subjects:
  - kind: ServiceAccount
    name: argo-events-sa
roleRef:
  kind: Role
  name: argo-events-role
  apiGroup: rbac.authorization.k8s.io
