apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: working-sensor
  namespace: jallybean-telemetry
spec:
  dependencies:
    - name: example-dep
      eventSourceName: working-eventsource
      eventName: example
  triggers:
    - template:
        name: tekton-pipeline-trigger
        k8s:
          group: tekton.dev
          version: v1beta1
          resource: pipelineruns
          operation: create
          source:
            resource:
              apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                generateName: example-pipelinerun-
              spec:
                pipelineRef:
                  name: example-pipeline
                params:
                  - name: event-id
                    value: "{{inputs.parameters.event-id}}"
                  - name: metric-value
                    value: "{{inputs.parameters.metric-value}}"
      parameters:
        - src:
            dependencyName: example-dep
            dataKey: body.event_id
          dest: spec.params[0].value
        - src:
            dependencyName: example-dep
            dataKey: body.metric_value
          dest: spec.params[1].value