apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-ingestor
  namespace: jallybean-telemetry
  labels:
    app: telemetry-ingestor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-ingestor
  template:
    metadata:
      labels:
        app: telemetry-ingestor
        jallybean_audit: "true"
    spec:
      serviceAccountName: telemetry-ingestor
      containers:
        - name: api
          image: kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          args: []
          ports:
            - containerPort: 80
          resources:
            requests: { cpu: "100m", memory: "128Mi" }
            limits: { cpu: "500m", memory: "512Mi" }
