apiVersion: v1
kind: Service
metadata:
  name: telemetry-ingestor
  namespace: jallybean-telemetry
spec:
  type: ClusterIP
  selector:
    app: telemetry-ingestor
  ports:
    - name: http
      port: 80
      targetPort: 80
