apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: telemetryvalues.jallybean.telemetry
spec:
  group: jallybean.telemetry
  names:
    kind: TelemetryValue
    plural: telemetryvalues
    singular: telemetryvalue
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          value:
            type: number
