apiVersion: v1
kind: ServiceAccount
metadata:
  name: telemetry-ingestor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: telemetry-read
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: telemetry-read-binding
subjects:
  - kind: ServiceAccount
    name: telemetry-ingestor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: telemetry-read
